name: Build & Push Docker (ARM64+AMD64)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      # Login to GHCR with an org-scoped PAT (write:packages, read:packages; SSO authorized)
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: qsc-jmurr
          password: ${{ secrets.GHCR_PAT }}

      # Build & push to BOTH namespaces (org + your user)
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ghcr.io/qsc-jmurr/qsys-uk-experience-centre:latest
          build-args: |
            NEXT_PUBLIC_CORE_IP=${{ vars.NEXT_PUBLIC_CORE_IP }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
